# Generated by Django 6.0.5 on 2026-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done')], default='new', max_length=20),
        ),
    ]
